### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [lhs4297/C202309#4]
### 없는 파일
- challenge/week6/studentGrade.c
- practice/week6/studentGrade.c
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week5/functionMulti
    - Warning: return type of 'main' is not 'int' [line 4]
        - main 함수에 반환형과 반환값을 추가해주세요.
- WARNING in practice/week5/functionHap
    - Warning: return type of 'main' is not 'int' [line 4]
        - main 함수에 반환형과 반환값을 추가해주세요.

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week5/functionMulti
- Insufficient comments in practice/week5/functionHap

**Comment by MisooKim2** [comment]
이현승 학생 안녕하세요.
결석 일자의 수업에서 해야할 실습을 업로드하지 않은 것으로 보입니다.
추가해서 업로드 해주세요.

**Comment by lhs4297** [comment]
해결했습니다 감사합니다.
